LOCAL_EVIDENCE_STORE = [
    {
        "id": "evidence_1",
        "title": "Eiffel Tower Location Note",
        "source_type": "local_demo_fact",
        "source_quality": "demo_verified",
        "source_score": 0.8,
        "url": "local://eiffel-tower-location",
        "text": "The Eiffel Tower is a landmark in Paris, France.",
    },
    {
        "id": "evidence_2",
        "title": "Berlin Capital Note",
        "source_type": "local_demo_fact",
        "source_quality": "demo_verified",
        "source_score": 0.8,
        "url": "local://berlin-capital",
        "text": "Berlin is the capital city of Germany.",
    },
    {
        "id": "evidence_3",
        "title": "Mars Nickname Note",
        "source_type": "local_demo_fact",
        "source_quality": "demo_verified",
        "source_score": 0.8,
        "url": "local://mars-red-planet",
        "text": "Mars is often called the Red Planet because of its reddish appearance.",
    },
    {
        "id": "evidence_4",
        "title": "Brazil Coffee Note",
        "source_type": "local_demo_fact",
        "source_quality": "demo_partial",
        "source_score": 0.5,
        "url": "local://brazil-coffee",
        "text": "Coffee is widely grown in Brazil today.",
    },
    {
        "id": "evidence_5",
        "title": "FIFA World Cup 2022 Winner Note",
        "source_type": "local_demo_fact",
        "source_quality": "demo_verified",
        "source_score": 0.8,
        "url": "local://fifa-world-cup-2022-winner",
        "text": "Argentina won the 2022 FIFA World Cup.",
    },
]
